config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'list', to: 'tasks#index'
  get "tasks/:id/edit", to: "tasks#edit", as: :edit
  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy"
  get "tasks/:id", to: "tasks#details", as: :task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

   before_action :set_task, only: [:details, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def details
  end

  def new
    @task = Task.new # needed to instantiate the form_for
  end

  def create
    @task = Task.new(task_params)
    @task.save
    # Will raise ActiveModel::ForbiddenAttributesError
    redirect_to list_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)
    # Will raise ActiveModel::ForbiddenAttributesError
    redirect_to list_path(@task)
  end

  def destroy
    @task.destroy
    # no need for app/views/restaurants/destroy.html.erb
    redirect_to list_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/details.html.erb
<h2><%= @task.title %></h2>
<p>Details: <%= @task.details %></p>
<p>Completed: <%= @task.completed %></p>

<p><%= link_to "Back to list", list_path %></p>
<p><%= link_to "Edit Task", edit_path(@task.id) %></p>

app/views/tasks/edit.html.erb
<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<ul>
  <% @tasks.each do |task| %>
    <li>
      <% if task.completed == true  %>
        <i class="fas fa-check"></i>
      <% else %>
        <i class="far fa-square"></i>
      <% end %> |
      <%= link_to "#{task.title}", task_path(task.id) %> |
      <%= link_to '<i class="fas fa-trash"></i>'.html_safe,
            task_path(task),
            method: :delete,
            data: { confirm: "Are you sure?" } %></li>
  <% end %>
</ul>

<p><%= link_to "+ Add A Task", tasks_new_path %></p>

app/views/tasks/new.html.erb
<%= render "form", task: @task %>